export const AbilitiesDescription = {
    "lc": [
        "Identificar linguagens e recursos expressivos como elementos de caracterização dos sistemas de comunicação",
        "Recorrer aos conhecimentos dos sistemas de comunicação para resolver problemas sociais.",
        "Relacionar informações considerando a sua função social",
        "Reconhecer posições críticas",
        "Associar vocábulos e expressões de um texto em Lingua estrangeira ao seu tema",
        "Utilizar os conhecimentos da Lingua estrangeira como meio de ampliar o acesso a informações.",
        "Relacionar um texto em Lingua estrangeira a sua função e uso social.",
        "Reconhecer a importância da produção cultural em Lingua estrangeira como representação da diversidade linguística",
        "Reconhecer as manifestações corporais como originárias de necessidades cotidianas de um grupo social",
        "Reconhecer a necessidade de transformação de hábitos corporais",
        "Reconhecer a linguagem corporal como meio de interação social, considerando os limites e as adaptações para diferentes indivíduos",
        "Reconhecer diferentes funções da arte em seus meios culturais",
        "Analisar as produções artísticas como meio de explicar diferentes culturas, padrões de beleza e preconceitos",
        "Reconhecer o valor da diversidade artística e das inter-relações de elementos",
        "Estabelecer relações entre o texto literário e o momento de sua produção",
        "Relacionar informações sobre concepções artísticas e procedimentos de construção do texto",
        "Reconhecer a presença de valores sociais no patrimônio literário nacional",
        "Identificar os elementos que promovem a progressão temática, organização e estruturação do texto",
        "Analisar a função da linguagem predominante nos textos em situações específicas de interlocução",
        "Reconhecer a importância do patrimônio linguístico para a preservação da identidade nacional",
        "Reconhecer recursos verbais e não-verbais utilizados para criar e mudar comportamentos e hábitos",
        "Relacionar, em diferentes textos, opiniões, temas, assuntos e recursos linguísticos",
        "Inferir em um texto quais são os objetivos de seu produtor pela análise dos argumentos utilizados.",
        "Reconhecer no texto estratégias argumentativas empregadas para o convencimento do público",
        "Identificar as marcas linguísticas que singularizam as variedades linguísticas sociais e regionais",
        "Relacionar as variedades linguísticas a situações específicas de uso social",
        "Reconhecer os usos da norma padrão da língua portuguesa nas diferentes situações de comunicação",
        "Reconhecer a função e o impacto social das diferentes tecnologias da comunicação e informação",
        "Identificar, pela análise de suas linguagens, as tecnologias da comunicação e informação",
        "Relacionar as tecnologias de comunicação e informação ao desenvolvimento das sociedades"
    ],
    "ch": [

    ],
    "cn": [

    ],
    "mt": [
        "Reconhecer diferentes significados e representações dos números e operações",
        "Identificar padrões numéricos ou princípios de contagem",
        "Resolver problemas envolvendo conhecimentos numéricos",
        "Avaliar a razoabilidade de um resultado numérico",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos numéricos",
        "Interpretar a movimentação no espaço tridimensional e sua representação no espaço bidimensional",
        "Identificar características de figuras planas ou espaciais",
        "Resolver problemas que envolvam conhecimentos geométricos de espaço e forma",
        "Utilizar conhecimentos geométricos de espaço e forma na solução de problemas do cotidiano",
        "Identificar relações entre grandezas e unidades de medida",
        "Utilizar a noção de escalas na leitura de representação de situação do cotidiano",
        "Resolver problemas que envolvam medidas de grandezas",
        "Avaliar o resultado de uma medição na construção de um argumento consistente",
        "Avaliar intervenções na realidade com conhecimentos geométricos relacionados a grandezas e medidas",
        "Identificar a relação de dependência entre grandezas",
        "Resolver problemas envolvendo a variação de grandezas, direta ou inversamente proporcionais",
        "Analisar informações envolvendo a variação de grandezas",
        "Avaliar propostas de intervenção na realidade envolvendo variação de grandezas",
        "Identificar representações algébricas que expressem a relação entre grandezas",
        "Interpretar gráfico cartesiano que represente relações entre grandezas",
        "Resolver problemas cuja modelagem envolva conhecimentos algébricos",
        "Utilizar conhecimentos algébricos/geométricos para a construção de argumentação",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos algébricos",
        "Utilizar informações expressas em gráficos/tabelas para fazer inferências",
        "Resolver problema com dados apresentados em tabelas/gráficos",
        "Analisar informações expressas em gráficos/tabelas para a construção de argumentos",
        "Calcular medidas de tendência central ou de dispersão de um conjunto de dados",
        "Resolver problemas que envolvam conhecimentos de estatística e probabilidade",
        "Utilizar conhecimentos de estatística e probabilidade para a construção de argumentação",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos de estatística e probabilidade"
    ]
}