export const AbilitiesDescription = {
    "lc": [
        "Identificar linguagens e recursos expressivos como elementos de caracterização dos sistemas de comunicação",
        "Recorrer aos conhecimentos dos sistemas de comunicação para resolver problemas sociais.",
        "Relacionar informações considerando a sua função social",
        "Reconhecer posições críticas",
        "Associar vocábulos e expressões de um texto em Lingua estrangeira ao seu tema",
        "Utilizar os conhecimentos da Lingua estrangeira como meio de ampliar o acesso a informações.",
        "Relacionar um texto em Lingua estrangeira a sua função e uso social.",
        "Reconhecer a importância da produção cultural em Lingua estrangeira como representação da diversidade linguística",
        "Reconhecer as manifestações corporais como originárias de necessidades cotidianas de um grupo social",
        "Reconhecer a necessidade de transformação de hábitos corporais",
        "Reconhecer a linguagem corporal como meio de interação social, considerando os limites e as adaptações para diferentes indivíduos",
        "Reconhecer diferentes funções da arte em seus meios culturais",
        "Analisar as produções artísticas como meio de explicar diferentes culturas, padrões de beleza e preconceitos",
        "Reconhecer o valor da diversidade artística e das inter-relações de elementos",
        "Estabelecer relações entre o texto literário e o momento de sua produção",
        "Relacionar informações sobre concepções artísticas e procedimentos de construção do texto",
        "Reconhecer a presença de valores sociais no patrimônio literário nacional",
        "Identificar os elementos que promovem a progressão temática, organização e estruturação do texto",
        "Analisar a função da linguagem predominante nos textos em situações específicas de interlocução",
        "Reconhecer a importância do patrimônio linguístico para a preservação da identidade nacional",
        "Reconhecer recursos verbais e não-verbais utilizados para criar e mudar comportamentos e hábitos",
        "Relacionar, em diferentes textos, opiniões, temas, assuntos e recursos linguísticos",
        "Inferir em um texto quais são os objetivos de seu produtor pela análise dos argumentos utilizados.",
        "Reconhecer no texto estratégias argumentativas empregadas para o convencimento do público",
        "Identificar as marcas linguísticas que singularizam as variedades linguísticas sociais e regionais",
        "Relacionar as variedades linguísticas a situações específicas de uso social",
        "Reconhecer os usos da norma padrão da língua portuguesa nas diferentes situações de comunicação",
        "Reconhecer a função e o impacto social das diferentes tecnologias da comunicação e informação",
        "Identificar, pela análise de suas linguagens, as tecnologias da comunicação e informação",
        "Relacionar as tecnologias de comunicação e informação ao desenvolvimento das sociedades"
    ],
    "ch": [
        "Interpretar historicamente e/ou geograficamente fontes documentais acerca de aspectos da cultura",
        "Analisar a produção da memória pelas sociedades humanas",
        "Associar as manifestações culturais do presente aos seus processos históricos",
        "Comparar pontos de vista expressos em diferentes fontes sobre determinado aspecto da cultura",
        "Identificar as manifestações da diversidade do patrimônio cultural em diferentes sociedades",
        "Interpretar diferentes representações gráficas e cartográficas dos espaços geográficos",
        "Identificar os significados histórico-geográficos das relações de poder entre as nações",
        "Analisar a ação das nações em relação à dinâmica dos fluxos populacionais e no enfrentamento de problemas sociais.",
        "Comparar o significado histórico-geográfico das organizações políticas e socioeconômicas",
        "Reconhecer a dinâmica dos movimentos sociais e a importância da coletividade na transformação da realidade",
        "Identificar registros de práticas de grupos sociais no tempo e no espaço",
        "Analisar o papel da justiça como instituição na organização das sociedades",
        "Analisar a atuação dos movimentos sociais que contribuíram para rupturas em disputas pelo poder",
        "Comparar diferentes pontos de vista sobre situação ou fatos de natureza histórica acerca das instituições",
        "Avaliar criticamente conflitos culturais, sociais e econômicos ao longo da história",
        "Identificar registros sobre o papel das técnicas e tecnologias na organização do trabalho",
        "Analisar fatores que explicam o impacto das novas tecnologias no processo de territorialização da produção",
        "Analisar diferentes processos de produção ou circulação de riquezas e suas implicações",
        "Reconhecer as transformações técnicas que determinam as formas de uso dos espaços rural e urbano",
        "Selecionar argumentos favoráveis ou contrários às modificações impostas pelas novas tecnologias",
        "Identificar o papel dos meios de comunicação na construção da vida social",
        "Analisar as lutas sociais e conquistas obtidas no que se refere às mudanças nas legislações",
        "Analisar a importância dos valores éticos na estruturação política das sociedades",
        "Relacionar cidadania e democracia na organização das sociedades",
        "Identificar estratégias que promovam formas de inclusão social",
        "Identificar o processo de ocupação dos meios físicos e as relações da vida humana com a paisagem",
        "Analisar de maneira crítica as interações da sociedade com o meio físico",
        "Relacionar o uso das tecnologias com os impactos sócio-ambientais em diferentes contextos",
        "Reconhecer a função dos recursos naturais na produção do espaço geográfico",
        "Avaliar as relações entre preservação e degradação da vida no planeta nas diferentes escalas"
    ],
    "cn": [
        "Reconhecer características ou propriedades de fenômenos ondulatórios ou oscilatórios",
        "Associar a solução de problemas com o correspondente desenvolvimento científico e tecnológico",
        "Confrontar interpretações científicas com interpretações baseadas no senso comum",
        "Avaliar propostas de intervenção, considerando a qualidade de vida e preservação da biodiversidade",
        "Dimensionar circuitos ou dispositivos elétricos de uso cotidiano",
        "Compreender manuais de utilização de aparelhos de uso comum",
        "Selecionar testes de controle para a comparação de materiais e produtos, tendo em vista a qualidade de vida.",
        "Identificar etapas em processos de utilização de matérias-primas, considerando processos biológicos, químicos ou físicos",
        "Compreender a importância dos ciclos biogeoquímicos ou do fluxo energia para a vida",
        "Analisar perturbações ambientais e prever efeitos em sistemas naturais ou sociais",
        "Reconhecer benefícios, limitações e aspectos éticos da biotecnologia",
        "Avaliar impactos em ambientes naturais decorrentes de atividades sociais ou econômicas",
        "Reconhecer mecanismos de transmissão da vida, explicando características dos seres vivos",
        "Identificar padrões em fenômenos e processos vitais dos organismos",
        "Interpretar modelos e experimentos para explicar fenômenos biológicos",
        "Compreender o papel da evolução na produção de padrões e processos biológicos",
        "Relacionar informações apresentadas em diferentes formas de linguagem e representação usadas nas ciências físicas, químicas ou biológicas",
        "Relacionar propriedades físicas, químicas ou biológicas de produtos às finalidades a que se destinam",
        "Avaliar processos das ciências naturais que contribuam para solucionar problemas de ordem social",
        "Caracterizar causas ou efeitos dos movimentos de partículas, objetos ou corpos celestes",
        "Utilizar leis físicas e químicas para interpretar processos inseridos no contexto da termodinâmica e do eletromagnetismo",
        "Compreender fenômenos decorrentes da interação entre a radiação e a matéria",
        "Avaliar possibilidades de geração, uso ou transformação de energia em ambientes específicos",
        "Utilizar códigos da química para caracterizar materiais, substâncias e transformações",
        "Caracterizar materiais identificando etapas, rendimentos ou implicações de sua obtenção ou produção",
        "Avaliar implicações sociais, ambientais e/ou econômicas na produção ou no consumo de recursos energéticos ou minerais",
        "Avaliar propostas de intervenção no meio ambiente aplicando conhecimentos químicos",
        "Associar características adaptativas dos organismos com seu modo de vida ou com seus limites de distribuição em diferentes ambientes",
        "Interpretar experimentos ou técnicas que utilizam seres vivos",
        "Avaliar propostas de alcance individual ou coletivo, identificando aquelas que visam à preservação"
    ],
    "mt": [
        "Reconhecer diferentes significados e representações dos números e operações",
        "Identificar padrões numéricos ou princípios de contagem",
        "Resolver problemas envolvendo conhecimentos numéricos",
        "Avaliar a razoabilidade de um resultado numérico",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos numéricos",
        "Interpretar a movimentação no espaço tridimensional e sua representação no espaço bidimensional",
        "Identificar características de figuras planas ou espaciais",
        "Resolver problemas que envolvam conhecimentos geométricos de espaço e forma",
        "Utilizar conhecimentos geométricos de espaço e forma na solução de problemas do cotidiano",
        "Identificar relações entre grandezas e unidades de medida",
        "Utilizar a noção de escalas na leitura de representação de situação do cotidiano",
        "Resolver problemas que envolvam medidas de grandezas",
        "Avaliar o resultado de uma medição na construção de um argumento consistente",
        "Avaliar intervenções na realidade com conhecimentos geométricos relacionados a grandezas e medidas",
        "Identificar a relação de dependência entre grandezas",
        "Resolver problemas envolvendo a variação de grandezas, direta ou inversamente proporcionais",
        "Analisar informações envolvendo a variação de grandezas",
        "Avaliar propostas de intervenção na realidade envolvendo variação de grandezas",
        "Identificar representações algébricas que expressem a relação entre grandezas",
        "Interpretar gráfico cartesiano que represente relações entre grandezas",
        "Resolver problemas cuja modelagem envolva conhecimentos algébricos",
        "Utilizar conhecimentos algébricos/geométricos para a construção de argumentação",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos algébricos",
        "Utilizar informações expressas em gráficos/tabelas para fazer inferências",
        "Resolver problema com dados apresentados em tabelas/gráficos",
        "Analisar informações expressas em gráficos/tabelas para a construção de argumentos",
        "Calcular medidas de tendência central ou de dispersão de um conjunto de dados",
        "Resolver problemas que envolvam conhecimentos de estatística e probabilidade",
        "Utilizar conhecimentos de estatística e probabilidade para a construção de argumentação",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos de estatística e probabilidade"
    ]
}