export const AbilitiesDescription = {
    "lc": [
        "Caracterização dos sistemas de comunicação",
        "Problema social",
        "Função social",
        "Posição crítica",
        "Vocábulos e Expressões - LÍNGUA ESTRANGEIRA",
        "Ampliação de acesso a informação - LÍNGUA ESTRANGEIRA",
        "Função e uso social - LÍNGUA ESTRANGEIRA",
        "Diversidade cultural e línguistica - LÍNGUA ESTRANGEIRA",
        "Necessidades corporais de um grupo social",
        "Transformação de hábitos corporais",
        "Interação social e adaptação através da linguagem corporal",
        "Diferentes funções da arte",
        "Relação da arte e cultura, padrão de beleza e preconceito",
        "Diversidade artísticas e inter-relação de elementos",
        "Texto literário e a relação com o momento de sua produção",
        "Procedimentos de construção do texto literário",
        "Patrimônio literário nacional",
        "Progressão temática",
        "Funções da linguagem",
        "Patrimônio linguístico para a preservação da identidade nacional",
        "Recursos verbais e não-verbais",
        "Relacionar opiniões, temas e recursos linguísticos",
        "Análise de procedimentos argumentativos",
        "Reconhecer estratégias argumentativas para convencer o público",
        "Identificar marcas linguísticas",
        "Relacionar a variedade linguística a situações específicas de uso social",
        "Norma padrão",
        "Função e impacto social das tecnologias da comunicação e informação",
        "Identificar tecnologias de comunicação e informação",
        "Relacionar tecnologias de comunicação e informação ao desenvolvimento da sociedade"
    ],
    "ch": [

    ],
    "cn": [

    ],
    "mt": [
        "Reconhecer diferentes significados e representações dos números e operações",
        "Identificar padrões numéricos ou princípios de contagem",
        "Resolver problemas envolvendo conhecimentos numéricos",
        "Avaliar a razoabilidade de um resultado numérico",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos numéricos",
        "Interpretar a movimentação no espaço tridimensional e sua representação no espaço bidimensional",
        "Identificar características de figuras planas ou espaciais",
        "Resolver problemas que envolvam conhecimentos geométricos de espaço e forma",
        "Utilizar conhecimentos geométricos de espaço e forma na solução de problemas do cotidiano",
        "Identificar relações entre grandezas e unidades de medida",
        "Utilizar a noção de escalas na leitura de representação de situação do cotidiano",
        "Resolver problemas que envolvam medidas de grandezas",
        "Avaliar o resultado de uma medição na construção de um argumento consistente",
        "Avaliar intervenções na realidade com conhecimentos geométricos relacionados a grandezas e medidas",
        "Identificar a relação de dependência entre grandezas",
        "Resolver problemas envolvendo a variação de grandezas, direta ou inversamente proporcionais",
        "Analisar informações envolvendo a variação de grandezas",
        "Avaliar propostas de intervenção na realidade envolvendo variação de grandezas",
        "Identificar representações algébricas que expressem a relação entre grandezas",
        "Interpretar gráfico cartesiano que represente relações entre grandezas",
        "Resolver problemas cuja modelagem envolva conhecimentos algébricos",
        "Utilizar conhecimentos algébricos/geométricos para a construção de argumentação",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos algébricos",
        "Utilizar informações expressas em gráficos/tabelas para fazer inferências",
        "Resolver problema com dados apresentados em tabelas/gráficos",
        "Analisar informações expressas em gráficos/tabelas para a construção de argumentos",
        "Calcular medidas de tendência central ou de dispersão de um conjunto de dados",
        "Resolver problemas que envolvam conhecimentos de estatística e probabilidade",
        "Utilizar conhecimentos de estatística e probabilidade para a construção de argumentação",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos de estatística e probabilidade"
    ]
}